image: registry.gitlab.com/florianpose/containerfabrik/alarmdisplay:latest

test:
    script:
        - flake8 --ignore=E123,E126,E128,E251,E261,E265,E301,E302,E303,E402,E502,W605,E722
        - python test.py
